version: '3.6'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: java123
      POSTGRES_DB: employees

  app:
    image: benben159/spring-demo2
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./app-docker.properties:/app-docker.properties
